from typing import TypeVar, Protocol

T = TypeVar("T", contravariant=True)


class Comparable(Protocol[T]):
    """A *comparable* protocol, one that supports <,>,= etc"""

    def __lt__(self, other: T, /) -> bool: ...
    def __gt__(self, other: T, /) -> bool: ...
    def __le__(self, other: T, /) -> bool: ...
    def __ge__(self, other: T, /) -> bool: ...
